[package]
name = "snake-game"
version = "0.1.0"
authors = ["Alexey Velikiy <av@corpglory.com>"]
edition = "2018"

[dependencies]
amethyst = "0.12.0"

[features]
default = ["vulkan"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
nightly = ["amethyst/nightly"]